version: '3.9'

services:
  # Django Spending Analysis
  web:
    build: .
    container_name: spending_analysis
    command: gunicorn spending_analysis.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - weasydeps

  weasydeps:
    image: alpine
    container_name: weasydeps
    command: tail -f /dev/null  # dummy container if you want to later separate GTK deps

volumes:
  static_volume:
