apiVersion: v1
kind: Service
metadata:
  name: spendinganalysis-service
spec:
  selector:
    app: spending-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
