# Generated by Django 5.2.4 on 2025-07-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spending_app', '0001_category_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transations',
            new_name='Transactions',
        ),
    ]
