# Generated by Django 5.2.4 on 2025-07-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_app', '0004_transaction_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='spending_app.transactionuploads'),
            preserve_default=False,
        ),
    ]
